### PR TITLE
v0.6.0

### LINKED ISSUE #30: Multiple Subaru accounts
I have what seems to be an outlier use case. That is, I'm trying to use this integration twice. We have two starlink accounts, that have separate users/pass/pin. Due to how the integration is written, it's not possible with the current code.

My first attempt at a quicker workaround was to fork this repo and then just change the domain and any other overlapping components. This seemed to work at first, but then I saw inconsistent where either one or the other account could perform remote services.

I think the ultimate issue can be traced to the aiohttp library creating an auth session against the API endpoint. This session seems to overlap between multiple integrations within the home assistant context. Such that if you add a new integration, no matter the domain, the session will be overwritten with the newer auth session.

I might be on my own here, but figured it was worth reaching out in case there were any ideas.
If you don't think this issue is relevant to the project, feel free to close, and I'll try to figure something out.

### LINKED ISSUE #32: Start service climate settings
No matter what I do(manually starting from the Subaru app from a preset or manually choosing climate settings), everytime I start from HA it always starts with my climate set to 65. In the summer, this wasn't really an issue, but now that it's cold out I really want the system to heat up my car and start melting snow. How can I change the default climate setting that the integration starts using?

### PR DESCRIPTION
**Pull request by G-Two**
## Breaking Changes
- `subaru.remote_start` service required data attributes have changed
  - `preset_name` is a new required data attribute to specify a climate control preset, see README
- All previous Subaru integration specific services are now deprecated and will be removed in a later release
  - Use the native HA services exposed by Button and Select for equivalent functionality (without the need to enter VIN) 

## New Features
- Remote command button entities and climate control selection is now supported (thanks for the idea @stboch)
- Add ability to unlock only driver's door or tailgate via a new `subaru.unlock_specific_door` service
- Added sunroof binary sensor (it doesn't work on my 2019 Crosstrek, but maybe it works for someone? Please leave feedback.)

## Miscellaneous
- Update to Subaru API g2v21 (used by most recent official mobile app, will hopefully be more stable)

## Related Issues
- Addresses https://github.com/G-Two/subarulink/issues/46
- Fixes #32
- Should hopefully fix? #29
- Fixes #30 (thanks for the solution @jd-daniels)
- Fixes https://github.com/G-Two/subarulink/issues/48
- Fixes https://github.com/G-Two/subarulink/issues/49

### CODE REVIEW

**Comment by stboch** [comment]
Remote Start working properly on 2020 Outback

**Comment by ACiDGRiM** [comment]
Remote Start with Climate Preset working on 2019 Ascent.

**Comment by stboch** [comment]
@G-Two Not sure exactly what the issue is as it seems to only be happening with "Selects" but one car is properly creating the Select however one of the other is not... I added a bunch of debug it looks like it never enters the options property for the class. 

`2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru] Finished fetching subaru_data data in 31.001 seconds (success: True)
2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru.select] Creating selects for 4S4BTAPC9XXXXXX and is RES True
2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru.select] Entering Successful if for 4S4BTAPC9XXXXXXX
2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru.select] init of Climate class 4S4BTAPC9XXXXXX
2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru.select] Creating selects for 4S4WMARD6XXXXXX and is RES True
2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru.select] Entering Successful if for 4S4WMARD6K3416559
2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru.select] init of Climate class 4S4WMARD6XXXXXX
2021-12-29 11:55:55 DEBUG (MainThread) [custom_components.subaru.select] Getting 4S4WMARD6XXXXXX climate data.`

**Comment by G-Two** [comment]
@stboch I'll probably need debug logs from subarulink to figure out the cause

**Comment by stboch** [comment]
@G-Two  I didn't include subarulink logs because the issue isn't the subaru side it seems like something with homeassistant.

**Comment by G-Two** [comment]
@stboch are the settings entities for both vehicles created?

**Comment by stboch** [comment]
@G-Two yeah, after finding the NULL presets bug I added a preset to move past it, and thats where it is only creating the select for one of the two cars. There doesn't seem to be anything specific about it thats why I added a bunch of debug to make sure it was following through the functions, but ultimately it seems like it initializes the car but doesn't enter into the defining the selects options.

But remote start service and everything still works, and when forcing the code to enter the climate function i get the data from subarulink for the car.

**Comment by G-Two** [comment]
@stboch can you paste your modified `select.py` (with the additional debug lines) so I can see where in the code the debug trace maps to? It's still not clear to me whether or not the second entity is created (just without any options to select from).

**Comment by stboch** [comment]
@G-Two https://gist.github.com/stboch/4f6acbb9588432de3d8d32ba0d8429d9

**Comment by G-Two** [comment]
Ok I see the problem in `async_setup_entry`. `climate_select` needs to be its own list and each new entity needs to be appended to it. Otherwise only the last vehicle will be added to hass. It’ll be any easy fix.

**Comment by stboch** [comment]
Looks great over here. New fixes working perfectly.

**Comment by FerriteGiant** [comment]
Remote Start is working on my 2019 Forester. The sunroof binary sensor doesn't show up for me.

**Pull request merged**
